export interface GrammarLesson {
  id: string;
  level: "A1-A2" | "B1-B2" | "C1-C2";
  category: string;
  titleEn: string;
  titleVi: string;
  description: string;
  slug: string; // Dynamic route: /grammar/<slug>
  aiKeywords: string[]; // bọc vào prompt cho Claude Explainer
}

export const LEVELS = ["A1-A2", "B1-B2", "C1-C2"] as const;

export const grammarLessons: GrammarLesson[] = [
  // ===== GIAI ĐOẠN 1: SƠ CẤP (A1-A2) =====
  {
    id: "g-a1-01",
    level: "A1-A2",
    category: "Nouns & Pronouns",
    titleEn: "Singular and Plural Nouns",
    titleVi: "Danh từ Số ít và Danh từ Số nhiều",
    description: "Cách phân biệt và thêm s/es vào sau danh từ.",
    slug: "singular-plural-nouns",
    aiKeywords: ["Singular nouns", "Plural nouns", "Regular plural rules", "Irregular plurals"],
  },
  {
    id: "g-a1-02",
    level: "A1-A2",
    category: "Nouns & Pronouns",
    titleEn: "Countable and Uncountable Nouns",
    titleVi: "Danh từ Đếm được và Không đếm được",
    description: "Nhận biết danh từ đếm được và các danh từ trừu tượng, chất lỏng không đếm được.",
    slug: "countable-uncountable-nouns",
    aiKeywords: ["Countable nouns", "Uncountable nouns", "How much", "How many"],
  },
  {
    id: "g-a1-03",
    level: "A1-A2",
    category: "Nouns & Pronouns",
    titleEn: "Personal & Possessive Pronouns",
    titleVi: "Đại từ Nhân xưng và Đại từ Sở hữu",
    description: "Cách dùng I, you, we, they và mine, yours, hers, his.",
    slug: "personal-possessive-pronouns",
    aiKeywords: ["Subject pronouns", "Object pronouns", "Possessive adjectives", "Possessive pronouns"],
  },
  {
    id: "g-a1-04",
    level: "A1-A2",
    category: "Articles & Determiners",
    titleEn: "Articles: A, An, The",
    titleVi: "Mạo từ: A, An, The",
    description: "Quy tắc dùng mạo từ xác định và bất định trong câu.",
    slug: "articles-a-an-the",
    aiKeywords: ["Indefinite articles a an", "Definite article the", "Zero article"],
  },
  {
    id: "g-a1-05",
    level: "A1-A2",
    category: "Articles & Determiners",
    titleEn: "Demonstratives & Quantifiers",
    titleVi: "Từ Chỉ định và Từ Chỉ số lượng cơ bản",
    description: "Cách dùng This/That/These/Those và Some/Any/Much/Many.",
    slug: "demonstratives-quantifiers",
    aiKeywords: ["This that these those", "Some and Any", "Much and Many", "A lot of"],
  },
  {
    id: "g-a1-06",
    level: "A1-A2",
    category: "Verbs & Tenses",
    titleEn: "The Verb 'To Be'",
    titleVi: "Động từ 'To Be' ở Hiện tại và Quá khứ",
    description: "Cách chia Am/Is/Are và Was/Were trong các câu đơn giản.",
    slug: "verb-to-be",
    aiKeywords: ["Verb to be", "Am Is Are", "Was Were", "To Be negative and questions"],
  },
  {
    id: "g-a1-07",
    level: "A1-A2",
    category: "Verbs & Tenses",
    titleEn: "Present Simple Tense",
    titleVi: "Thì Hiện tại Đơn",
    description: "Diễn tả thói quen, hành động lặp đi lặp lại và sự thật hiển nhiên.",
    slug: "present-simple",
    aiKeywords: ["Present Simple", "Habits", "General truths", "Do and Does"],
  },
  {
    id: "g-a1-08",
    level: "A1-A2",
    category: "Verbs & Tenses",
    titleEn: "Present Continuous Tense",
    titleVi: "Thì Hiện tại Tiếp diễn",
    description: "Diễn tả hành động đang xảy ra ngay tại thời điểm nói.",
    slug: "present-continuous",
    aiKeywords: ["Present Continuous", "Action happening now", "Am Is Are + V-ing", "Temporary situations"],
  },
  {
    id: "g-a1-09",
    level: "A1-A2",
    category: "Verbs & Tenses",
    titleEn: "Past Simple Tense",
    titleVi: "Thì Quá khứ Đơn",
    description: "Diễn tả hành động đã xảy ra và chấm dứt hoàn toàn trong quá khứ.",
    slug: "past-simple",
    aiKeywords: ["Past Simple", "Regular verbs ed", "Irregular verbs", "Did and Didn't"],
  },
  {
    id: "g-a1-10",
    level: "A1-A2",
    category: "Verbs & Tenses",
    titleEn: "Future with Will and Be Going To",
    titleVi: "Thì Tương lai: Will và Be Going To",
    description: "Phân biệt quyết định bộc phát (Will) và kế hoạch có sẵn (Be going to).",
    slug: "future-will-be-going-to",
    aiKeywords: ["Future simple will", "Be going to plan", "Spontaneous decisions", "Predictions"],
  },
  {
    id: "g-a1-11",
    level: "A1-A2",
    category: "Modifiers",
    titleEn: "Adjectives and Adverbs base",
    titleVi: "Tính từ và Trạng từ Cơ bản",
    description: "Vị trí của tính từ và cách hình thành trạng từ chỉ cách thức (-ly).",
    slug: "adjectives-adverbs-basic",
    aiKeywords: ["Adjective positions", "Adverbs of manner", "Adverbs of frequency"],
  },
  {
    id: "g-a1-12",
    level: "A1-A2",
    category: "Prepositions",
    titleEn: "Prepositions of Time and Place",
    titleVi: "Giới từ chỉ Thời gian và Nơi chốn",
    description: "Mẹo làm chủ bộ ba giới từ In, On, At.",
    slug: "prepositions-in-on-at",
    aiKeywords: ["Prepositions of place", "Prepositions of time", "In On At rules"],
  },
  {
    id: "g-a1-13",
    level: "A1-A2",
    category: "Sentence Structures",
    titleEn: "Basic Sentence Structure & Questions",
    titleVi: "Cấu trúc Câu cơ bản và Câu hỏi",
    description: "Cách tạo câu khẳng định, phủ định, câu hỏi Yes/No và câu hỏi Wh-.",
    slug: "basic-sentence-questions",
    aiKeywords: ["Subject Verb Object", "Wh- questions", "Yes No questions", "Imperatives"],
  },

  // ===== GIAI ĐOẠN 2: TRUNG CẤP (B1-B2) =====
  {
    id: "g-b1-01",
    level: "B1-B2",
    category: "Verbs & Tenses",
    titleEn: "Present Perfect Tense",
    titleVi: "Thì Hiện tại Hoàn thành",
    description: "Diễn tả kinh nghiệm, trải nghiệm hoặc hành động kéo dài từ quá khứ đến hiện tại.",
    slug: "present-perfect",
    aiKeywords: ["Present Perfect", "Have Has + V3", "Since and For", "Life experiences"],
  },
  {
    id: "g-b1-02",
    level: "B1-B2",
    category: "Verbs & Tenses",
    titleEn: "Past Continuous Tense",
    titleVi: "Thì Quá khứ Tiếp diễn",
    description: "Hành động đang xảy ra tại một thời điểm cụ thể trong quá khứ hoặc bị hành động khác xen vào.",
    slug: "past-continuous",
    aiKeywords: ["Past Continuous", "Was Were + V-ing", "Interrupted actions", "When and While"],
  },
  {
    id: "g-b1-03",
    level: "B1-B2",
    category: "Verbs & Tenses",
    titleEn: "Past Perfect Tense",
    titleVi: "Thì Quá khứ Hoàn thành",
    description: "Diễn tả hành động xảy ra và hoàn thành trước một hành động khác trong quá khứ.",
    slug: "past-perfect",
    aiKeywords: ["Past Perfect", "Had + V3", "Action before past", "By the time"],
  },
  {
    id: "g-b1-04",
    level: "B1-B2",
    category: "Verbs & Tenses",
    titleEn: "Future Continuous & Future Perfect",
    titleVi: "Thì Tương lai Tiếp diễn và Tương lai Hoàn thành",
    description: "Hành động đang diễn ra hoặc đã hoàn thành tại một thời điểm trong tương lai.",
    slug: "advanced-future-tenses",
    aiKeywords: ["Future Continuous", "Future Perfect", "Will be V-ing", "Will have V3"],
  },
  {
    id: "g-b1-05",
    level: "B1-B2",
    category: "Voice & Speech",
    titleEn: "Passive Voice",
    titleVi: "Câu Bị động",
    description: "Nhấn mạnh vào hành động hoặc đối tượng chịu tác động thay vì người thực hiện.",
    slug: "passive-voice",
    aiKeywords: ["Passive Voice", "Be + Past Participle", "By agent", "Passive with modals"],
  },
  {
    id: "g-b1-06",
    level: "B1-B2",
    category: "Voice & Speech",
    titleEn: "Reported Speech",
    titleVi: "Câu Gián tiếp / Câu Tường thuật",
    description: "Cách kể lại lời nói của người khác (Quy tắc lùi thì, đổi đại từ và trạng từ).",
    slug: "reported-speech",
    aiKeywords: ["Reported Speech", "Tense shifting", "Indirect speech", "Reporting verbs"],
  },
  {
    id: "g-b1-07",
    level: "B1-B2",
    category: "Clauses",
    titleEn: "Defining & Non-Defining Relative Clauses",
    titleVi: "Mệnh đề Quan hệ Xác định và Không xác định",
    description: "Cách dùng Who, Whom, Which, That, Whose để nối câu và bổ nghĩa cho danh từ.",
    slug: "relative-clauses",
    aiKeywords: ["Relative Clauses", "Relative pronouns", "Defining relative", "Non-defining commas"],
  },
  {
    id: "g-b1-08",
    level: "B1-B2",
    category: "Conditionals",
    titleEn: "Conditionals: Type 0, 1, 2, 3",
    titleVi: "Câu Điều kiện từ Loại 0 đến Loại 3",
    description: "Hệ thống các câu giả thuyết từ có thật đến hoàn toàn trái ngược với quá khứ.",
    slug: "conditionals-all-types",
    aiKeywords: ["Conditionals", "Zero conditional", "First conditional", "Second conditional", "Third conditional"],
  },
  {
    id: "g-b1-09",
    level: "B1-B2",
    category: "Conditionals",
    titleEn: "Wishes and Regrets (Wish / If only)",
    titleVi: "Câu Ước và Nuối tiếc",
    description: "Cách diễn tả mong muốn trái với thực tế ở hiện tại, tương lai hoặc quá khứ.",
    slug: "wish-if-only",
    aiKeywords: ["Wish clauses", "If only", "Unreal present wish", "Past regret wish"],
  },
  {
    id: "g-b1-10",
    level: "B1-B2",
    category: "Modals",
    titleEn: "Modal Verbs & Modal of Deduction",
    titleVi: "Động từ Khuyết thiếu và Động từ Dự đoán",
    description: "Cách dùng can, must, should và cách suy đoán hiện tại (must be, can't be).",
    slug: "modal-verbs-deduction",
    aiKeywords: ["Modal verbs", "Modals of obligation", "Modals of deduction", "Must be / Can't be"],
  },
  {
    id: "g-b1-11",
    level: "B1-B2",
    category: "Verb Forms",
    titleEn: "Gerunds and Infinitives",
    titleVi: "Danh động từ (V-ing) và Động từ Nguyên thể (To V)",
    description: "Quy tắc đi sau các động từ đặc biệt và những từ thay đổi ý nghĩa (stop, remember, forget).",
    slug: "gerunds-infinitives",
    aiKeywords: ["Gerund V-ing", "Infinitive to-V", "Verbs changing meaning", "Bare infinitive"],
  },
  {
    id: "g-b1-12",
    level: "B1-B2",
    category: "Modifiers",
    titleEn: "Comparisons: Higher, Highest & Equal",
    titleVi: "Các cấu trúc So sánh",
    description: "So sánh hơn, so sánh nhất với tính từ ngắn/dài và cấu trúc so sánh bằng.",
    slug: "comparisons",
    aiKeywords: ["Comparative adjectives", "Superlative adjectives", "As... as comparison", "Irregular modifiers"],
  },

  // ===== GIAI ĐOẠN 3: NÂNG CAO (C1-C2) =====
  {
    id: "g-c1-01",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Negative and Adverbial Inversion",
    titleVi: "Đảo ngữ với Trạng từ Phủ định",
    description: "Đảo trợ động từ lên trước chủ ngữ nhằm mục đích nhấn mạnh ý phủ định câu.",
    slug: "negative-inversion",
    aiKeywords: ["Inversion", "Negative adverbs", "Hardly had I", "No sooner than", "Under no circumstances"],
  },
  {
    id: "g-c1-02",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Inverted Conditionals",
    titleVi: "Đảo ngữ trong Câu điều kiện",
    description: "Lược bỏ 'If' và đảo Should, Were, Had lên đầu câu để viết văn trang trọng.",
    slug: "inverted-conditionals",
    aiKeywords: ["Inverted conditionals", "Should you need", "Were I to be", "Had I known"],
  },
  {
    id: "g-c1-03",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Cleft Sentences",
    titleVi: "Câu Chẻ (Câu Nhấn mạnh)",
    description: "Sử dụng cấu trúc 'It is/was... that' hoặc 'What...' để làm nổi bật một thành phần trong câu.",
    slug: "cleft-sentences",
    aiKeywords: ["Cleft sentences", "It-cleft", "What-cleft", "Emphatic structures"],
  },
  {
    id: "g-c1-04",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "The Subjunctive Mood",
    titleVi: "Thể Giả định (Câu Cầu khiến)",
    description: "Cấu trúc đi với động từ khuyên bảo, yêu cầu bắt buộc động từ vế sau ở dạng nguyên mẫu không chia.",
    slug: "subjunctive-mood",
    aiKeywords: ["Subjunctive mood", "Mandative subjunctive", "Suggest that S V-bare", "It is crucial that"],
  },
  {
    id: "g-c1-05",
    level: "C1-C2",
    category: "Clauses",
    titleEn: "Reduced Relative Clauses",
    titleVi: "Rút gọn Mệnh đề Quan hệ",
    description: "Sử dụng V-ing (chủ động), V3/ed (bị động) hoặc To-V để tinh gọn mệnh đề quan hệ.",
    slug: "reduced-relative-clauses",
    aiKeywords: ["Reduced relative clauses", "Participle phrases", "Active reduction V-ing", "Passive reduction V3"],
  },
  {
    id: "g-c1-06",
    level: "C1-C2",
    category: "Clauses",
    titleEn: "Reduced Adverbial Clauses (Participle Clauses)",
    titleVi: "Rút gọn Mệnh đề Trạng ngữ",
    description: "Lược bỏ chủ ngữ của mệnh đề phụ khi hai mệnh đề có cùng chủ từ.",
    slug: "reduced-adverbial-clauses",
    aiKeywords: ["Participle clauses", "Dangling modifiers", "Having + V3", "Simultaneous actions"],
  },
  {
    id: "g-c1-07",
    level: "C1-C2",
    category: "Conditionals",
    titleEn: "Mixed Conditionals",
    titleVi: "Câu Điều kiện Hỗn hợp",
    description: "Sự kết hợp giữa các mốc thời gian (Quá khứ ảnh hưởng đến Hiện tại và ngược lại).",
    slug: "mixed-conditionals",
    aiKeywords: ["Mixed conditionals", "Type 3 + Type 2", "Type 2 + Type 3", "Unreal past with present result"],
  },
  {
    id: "g-c1-08",
    level: "C1-C2",
    category: "Modals",
    titleEn: "Modals in the Past (Past Modals)",
    titleVi: "Động từ Khuyết thiếu trong Quá khứ",
    description: "Diễn tả sự nuối tiếc hoặc suy đoán một việc đã xảy ra (should have done, must have done).",
    slug: "past-modals",
    aiKeywords: ["Past modals", "Should have V3", "Must have V3", "Could have V3", "Modal perfect"],
  },
  {
    id: "g-c1-09",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Advanced Subject-Verb Agreement",
    titleVi: "Sự Hòa hợp Chủ ngữ - Động từ Nâng cao",
    description: "Giải quyết các chủ ngữ phức tạp như các cụm danh từ tập hợp, Neither/Nor, As well as.",
    slug: "advanced-subject-verb-agreement",
    aiKeywords: ["Subject-verb agreement", "Collective nouns", "Neither nor agreement", "Plural in form singular in construction"],
  },
  {
    id: "g-c1-10",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Emphasis & Fronting",
    titleVi: "Biện pháp Đảo thành phần câu (Fronting) và Nhấn mạnh",
    description: "Đảo tính từ, tân ngữ hoặc cụm giới từ lên đầu câu để tạo hiệu ứng văn học.",
    slug: "fronting-emphasis",
    aiKeywords: ["Fronting", "Emphatic do", "Inversion for emphasis", "Poetic word order"],
  },
];

export const grammarBySlug = (slug: string): GrammarLesson | undefined =>
  grammarLessons.find((l) => l.slug === slug);
