export interface GrammarLesson {
  id: string;
  level: "A1-A2" | "B1-B2" | "C1-C2";
  category: string;
  titleEn: string;
  titleVi: string;
  description: string;
  slug: string; // Dynamic route: /grammar/<slug>
  aiKeywords: string[]; // bọc vào prompt cho Claude Explainer
}

export const LEVELS = ["A1-A2", "B1-B2", "C1-C2"] as const;

export const grammarLessons: GrammarLesson[] = [
  // ===== GIAI ĐOẠN 1: SƠ CẤP (A1-A2) =====
  {
    id: "g-a1-01",
    level: "A1-A2",
    category: "Nouns & Pronouns",
    titleEn: "Singular and Plural Nouns",
    titleVi: "Danh từ Số ít và Danh từ Số nhiều",
    description: "Cách phân biệt và thêm s/es vào sau danh từ.",
    slug: "singular-plural-nouns",
    aiKeywords: ["Singular nouns", "Plural nouns", "Regular plural rules", "Irregular plurals"],
  },
  {
    id: "g-a1-02",
    level: "A1-A2",
    category: "Nouns & Pronouns",
    titleEn: "Countable and Uncountable Nouns",
    titleVi: "Danh từ Đếm được và Không đếm được",
    description: "Nhận biết danh từ đếm được và các danh từ trừu tượng, chất lỏng không đếm được.",
    slug: "countable-uncountable-nouns",
    aiKeywords: ["Countable nouns", "Uncountable nouns", "How much", "How many"],
  },
  {
    id: "g-a1-03",
    level: "A1-A2",
    category: "Nouns & Pronouns",
    titleEn: "Personal & Possessive Pronouns",
    titleVi: "Đại từ Nhân xưng và Đại từ Sở hữu",
    description: "Cách dùng I, you, we, they và mine, yours, hers, his.",
    slug: "personal-possessive-pronouns",
    aiKeywords: ["Subject pronouns", "Object pronouns", "Possessive adjectives", "Possessive pronouns"],
  },
  {
    id: "g-a1-04",
    level: "A1-A2",
    category: "Articles & Determiners",
    titleEn: "Articles: A, An, The",
    titleVi: "Mạo từ: A, An, The",
    description: "Quy tắc dùng mạo từ xác định và bất định trong câu.",
    slug: "articles-a-an-the",
    aiKeywords: ["Indefinite articles a an", "Definite article the", "Zero article"],
  },
  {
    id: "g-a1-05",
    level: "A1-A2",
    category: "Articles & Determiners",
    titleEn: "Demonstratives & Quantifiers",
    titleVi: "Từ Chỉ định và Từ Chỉ số lượng cơ bản",
    description: "Cách dùng This/That/These/Those và Some/Any/Much/Many.",
    slug: "demonstratives-quantifiers",
    aiKeywords: ["This that these those", "Some and Any", "Much and Many", "A lot of"],
  },
  {
    id: "g-a1-06",
    level: "A1-A2",
    category: "Verbs & Tenses",
    titleEn: "The Verb 'To Be'",
    titleVi: "Động từ 'To Be' ở Hiện tại và Quá khứ",
    description: "Cách chia Am/Is/Are và Was/Were trong các câu đơn giản.",
    slug: "verb-to-be",
    aiKeywords: ["Verb to be", "Am Is Are", "Was Were", "To Be negative and questions"],
  },
  {
    id: "g-a1-07",
    level: "A1-A2",
    category: "Verbs & Tenses",
    titleEn: "Present Simple Tense",
    titleVi: "Thì Hiện tại Đơn",
    description: "Diễn tả thói quen, hành động lặp đi lặp lại và sự thật hiển nhiên.",
    slug: "present-simple",
    aiKeywords: ["Present Simple", "Habits", "General truths", "Do and Does"],
  },
  {
    id: "g-a1-08",
    level: "A1-A2",
    category: "Verbs & Tenses",
    titleEn: "Present Continuous Tense",
    titleVi: "Thì Hiện tại Tiếp diễn",
    description: "Diễn tả hành động đang xảy ra ngay tại thời điểm nói.",
    slug: "present-continuous",
    aiKeywords: ["Present Continuous", "Action happening now", "Am Is Are + V-ing", "Temporary situations"],
  },
  {
    id: "g-a1-09",
    level: "A1-A2",
    category: "Verbs & Tenses",
    titleEn: "Past Simple Tense",
    titleVi: "Thì Quá khứ Đơn",
    description: "Diễn tả hành động đã xảy ra và chấm dứt hoàn toàn trong quá khứ.",
    slug: "past-simple",
    aiKeywords: ["Past Simple", "Regular verbs ed", "Irregular verbs", "Did and Didn't"],
  },
  {
    id: "g-a1-10",
    level: "A1-A2",
    category: "Verbs & Tenses",
    titleEn: "Future with Will and Be Going To",
    titleVi: "Thì Tương lai: Will và Be Going To",
    description: "Phân biệt quyết định bộc phát (Will) và kế hoạch có sẵn (Be going to).",
    slug: "future-will-be-going-to",
    aiKeywords: ["Future simple will", "Be going to plan", "Spontaneous decisions", "Predictions"],
  },
  {
    id: "g-a1-11",
    level: "A1-A2",
    category: "Modifiers",
    titleEn: "Adjectives and Adverbs base",
    titleVi: "Tính từ và Trạng từ Cơ bản",
    description: "Vị trí của tính từ và cách hình thành trạng từ chỉ cách thức (-ly).",
    slug: "adjectives-adverbs-basic",
    aiKeywords: ["Adjective positions", "Adverbs of manner", "Adverbs of frequency"],
  },
  {
    id: "g-a1-12",
    level: "A1-A2",
    category: "Prepositions",
    titleEn: "Prepositions of Time and Place",
    titleVi: "Giới từ chỉ Thời gian và Nơi chốn",
    description: "Mẹo làm chủ bộ ba giới từ In, On, At.",
    slug: "prepositions-in-on-at",
    aiKeywords: ["Prepositions of place", "Prepositions of time", "In On At rules"],
  },
  {
    id: "g-a1-13",
    level: "A1-A2",
    category: "Sentence Structures",
    titleEn: "Basic Sentence Structure & Questions",
    titleVi: "Cấu trúc Câu cơ bản và Câu hỏi",
    description: "Cách tạo câu khẳng định, phủ định, câu hỏi Yes/No và câu hỏi Wh-.",
    slug: "basic-sentence-questions",
    aiKeywords: ["Subject Verb Object", "Wh- questions", "Yes No questions", "Imperatives"],
  },

  // ===== GIAI ĐOẠN 2: TRUNG CẤP (B1-B2) =====
  {
    id: "g-b1-01",
    level: "B1-B2",
    category: "Verbs & Tenses",
    titleEn: "Present Perfect Tense",
    titleVi: "Thì Hiện tại Hoàn thành",
    description: "Diễn tả kinh nghiệm, trải nghiệm hoặc hành động kéo dài từ quá khứ đến hiện tại.",
    slug: "present-perfect",
    aiKeywords: ["Present Perfect", "Have Has + V3", "Since and For", "Life experiences"],
  },
  {
    id: "g-b1-02",
    level: "B1-B2",
    category: "Verbs & Tenses",
    titleEn: "Past Continuous Tense",
    titleVi: "Thì Quá khứ Tiếp diễn",
    description: "Hành động đang xảy ra tại một thời điểm cụ thể trong quá khứ hoặc bị hành động khác xen vào.",
    slug: "past-continuous",
    aiKeywords: ["Past Continuous", "Was Were + V-ing", "Interrupted actions", "When and While"],
  },
  {
    id: "g-b1-03",
    level: "B1-B2",
    category: "Verbs & Tenses",
    titleEn: "Past Perfect Tense",
    titleVi: "Thì Quá khứ Hoàn thành",
    description: "Diễn tả hành động xảy ra và hoàn thành trước một hành động khác trong quá khứ.",
    slug: "past-perfect",
    aiKeywords: ["Past Perfect", "Had + V3", "Action before past", "By the time"],
  },
  {
    id: "g-b1-04",
    level: "B1-B2",
    category: "Verbs & Tenses",
    titleEn: "Future Continuous & Future Perfect",
    titleVi: "Thì Tương lai Tiếp diễn và Tương lai Hoàn thành",
    description: "Hành động đang diễn ra hoặc đã hoàn thành tại một thời điểm trong tương lai.",
    slug: "advanced-future-tenses",
    aiKeywords: ["Future Continuous", "Future Perfect", "Will be V-ing", "Will have V3"],
  },
  {
    id: "g-b1-05",
    level: "B1-B2",
    category: "Voice & Speech",
    titleEn: "Passive Voice",
    titleVi: "Câu Bị động",
    description: "Nhấn mạnh vào hành động hoặc đối tượng chịu tác động thay vì người thực hiện.",
    slug: "passive-voice",
    aiKeywords: ["Passive Voice", "Be + Past Participle", "By agent", "Passive with modals"],
  },
  {
    id: "g-b1-06",
    level: "B1-B2",
    category: "Voice & Speech",
    titleEn: "Reported Speech",
    titleVi: "Câu Gián tiếp / Câu Tường thuật",
    description: "Cách kể lại lời nói của người khác (Quy tắc lùi thì, đổi đại từ và trạng từ).",
    slug: "reported-speech",
    aiKeywords: ["Reported Speech", "Tense shifting", "Indirect speech", "Reporting verbs"],
  },
  {
    id: "g-b1-07",
    level: "B1-B2",
    category: "Clauses",
    titleEn: "Defining & Non-Defining Relative Clauses",
    titleVi: "Mệnh đề Quan hệ Xác định và Không xác định",
    description: "Cách dùng Who, Whom, Which, That, Whose để nối câu và bổ nghĩa cho danh từ.",
    slug: "relative-clauses",
    aiKeywords: ["Relative Clauses", "Relative pronouns", "Defining relative", "Non-defining commas"],
  },
  {
    id: "g-b1-08",
    level: "B1-B2",
    category: "Conditionals",
    titleEn: "Conditionals: Type 0, 1, 2, 3",
    titleVi: "Câu Điều kiện từ Loại 0 đến Loại 3",
    description: "Hệ thống các câu giả thuyết từ có thật đến hoàn toàn trái ngược với quá khứ.",
    slug: "conditionals-all-types",
    aiKeywords: ["Conditionals", "Zero conditional", "First conditional", "Second conditional", "Third conditional"],
  },
  {
    id: "g-b1-09",
    level: "B1-B2",
    category: "Conditionals",
    titleEn: "Wishes and Regrets (Wish / If only)",
    titleVi: "Câu Ước và Nuối tiếc",
    description: "Cách diễn tả mong muốn trái với thực tế ở hiện tại, tương lai hoặc quá khứ.",
    slug: "wish-if-only",
    aiKeywords: ["Wish clauses", "If only", "Unreal present wish", "Past regret wish"],
  },
  {
    id: "g-b1-10",
    level: "B1-B2",
    category: "Modals",
    titleEn: "Modal Verbs & Modal of Deduction",
    titleVi: "Động từ Khuyết thiếu và Động từ Dự đoán",
    description: "Cách dùng can, must, should và cách suy đoán hiện tại (must be, can't be).",
    slug: "modal-verbs-deduction",
    aiKeywords: ["Modal verbs", "Modals of obligation", "Modals of deduction", "Must be / Can't be"],
  },
  {
    id: "g-b1-11",
    level: "B1-B2",
    category: "Verb Forms",
    titleEn: "Gerunds and Infinitives",
    titleVi: "Danh động từ (V-ing) và Động từ Nguyên thể (To V)",
    description: "Quy tắc đi sau các động từ đặc biệt và những từ thay đổi ý nghĩa (stop, remember, forget).",
    slug: "gerunds-infinitives",
    aiKeywords: ["Gerund V-ing", "Infinitive to-V", "Verbs changing meaning", "Bare infinitive"],
  },
  {
    id: "g-b1-12",
    level: "B1-B2",
    category: "Modifiers",
    titleEn: "Comparisons: Higher, Highest & Equal",
    titleVi: "Các cấu trúc So sánh",
    description: "So sánh hơn, so sánh nhất với tính từ ngắn/dài và cấu trúc so sánh bằng.",
    slug: "comparisons",
    aiKeywords: ["Comparative adjectives", "Superlative adjectives", "As... as comparison", "Irregular modifiers"],
  },

  // ===== GIAI ĐOẠN 3: NÂNG CAO (C1-C2) =====
  {
    id: "g-c1-01",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Negative and Adverbial Inversion",
    titleVi: "Đảo ngữ với Trạng từ Phủ định",
    description: "Đảo trợ động từ lên trước chủ ngữ nhằm mục đích nhấn mạnh ý phủ định câu.",
    slug: "negative-inversion",
    aiKeywords: ["Inversion", "Negative adverbs", "Hardly had I", "No sooner than", "Under no circumstances"],
  },
  {
    id: "g-c1-02",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Inverted Conditionals",
    titleVi: "Đảo ngữ trong Câu điều kiện",
    description: "Lược bỏ 'If' và đảo Should, Were, Had lên đầu câu để viết văn trang trọng.",
    slug: "inverted-conditionals",
    aiKeywords: ["Inverted conditionals", "Should you need", "Were I to be", "Had I known"],
  },
  {
    id: "g-c1-03",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Cleft Sentences",
    titleVi: "Câu Chẻ (Câu Nhấn mạnh)",
    description: "Sử dụng cấu trúc 'It is/was... that' hoặc 'What...' để làm nổi bật một thành phần trong câu.",
    slug: "cleft-sentences",
    aiKeywords: ["Cleft sentences", "It-cleft", "What-cleft", "Emphatic structures"],
  },
  {
    id: "g-c1-04",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "The Subjunctive Mood",
    titleVi: "Thể Giả định (Câu Cầu khiến)",
    description: "Cấu trúc đi với động từ khuyên bảo, yêu cầu bắt buộc động từ vế sau ở dạng nguyên mẫu không chia.",
    slug: "subjunctive-mood",
    aiKeywords: ["Subjunctive mood", "Mandative subjunctive", "Suggest that S V-bare", "It is crucial that"],
  },
  {
    id: "g-c1-05",
    level: "C1-C2",
    category: "Clauses",
    titleEn: "Reduced Relative Clauses",
    titleVi: "Rút gọn Mệnh đề Quan hệ",
    description: "Sử dụng V-ing (chủ động), V3/ed (bị động) hoặc To-V để tinh gọn mệnh đề quan hệ.",
    slug: "reduced-relative-clauses",
    aiKeywords: ["Reduced relative clauses", "Participle phrases", "Active reduction V-ing", "Passive reduction V3"],
  },
  {
    id: "g-c1-06",
    level: "C1-C2",
    category: "Clauses",
    titleEn: "Reduced Adverbial Clauses (Participle Clauses)",
    titleVi: "Rút gọn Mệnh đề Trạng ngữ",
    description: "Lược bỏ chủ ngữ của mệnh đề phụ khi hai mệnh đề có cùng chủ từ.",
    slug: "reduced-adverbial-clauses",
    aiKeywords: ["Participle clauses", "Dangling modifiers", "Having + V3", "Simultaneous actions"],
  },
  {
    id: "g-c1-07",
    level: "C1-C2",
    category: "Conditionals",
    titleEn: "Mixed Conditionals",
    titleVi: "Câu Điều kiện Hỗn hợp",
    description: "Sự kết hợp giữa các mốc thời gian (Quá khứ ảnh hưởng đến Hiện tại và ngược lại).",
    slug: "mixed-conditionals",
    aiKeywords: ["Mixed conditionals", "Type 3 + Type 2", "Type 2 + Type 3", "Unreal past with present result"],
  },
  {
    id: "g-c1-08",
    level: "C1-C2",
    category: "Modals",
    titleEn: "Modals in the Past (Past Modals)",
    titleVi: "Động từ Khuyết thiếu trong Quá khứ",
    description: "Diễn tả sự nuối tiếc hoặc suy đoán một việc đã xảy ra (should have done, must have done).",
    slug: "past-modals",
    aiKeywords: ["Past modals", "Should have V3", "Must have V3", "Could have V3", "Modal perfect"],
  },
  {
    id: "g-c1-09",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Advanced Subject-Verb Agreement",
    titleVi: "Sự Hòa hợp Chủ ngữ - Động từ Nâng cao",
    description: "Giải quyết các chủ ngữ phức tạp như các cụm danh từ tập hợp, Neither/Nor, As well as.",
    slug: "advanced-subject-verb-agreement",
    aiKeywords: ["Subject-verb agreement", "Collective nouns", "Neither nor agreement", "Plural in form singular in construction"],
  },
  {
    id: "g-c1-10",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Emphasis & Fronting",
    titleVi: "Biện pháp Đảo thành phần câu (Fronting) và Nhấn mạnh",
    description: "Đảo tính từ, tân ngữ hoặc cụm giới từ lên đầu câu để tạo hiệu ứng văn học.",
    slug: "fronting-emphasis",
    aiKeywords: ["Fronting", "Emphatic do", "Inversion for emphasis", "Poetic word order"],
  },

  // ===== BỔ SUNG: nhóm thực dụng =====
  {
    id: "g-b1-13",
    level: "B1-B2",
    category: "Phrasal Verbs & Collocations",
    titleEn: "Phrasal Verbs",
    titleVi: "Cụm động từ (Phrasal Verbs)",
    description: "Động từ + giới từ/trạng từ tạo nghĩa mới; loại tách được và không tách được.",
    slug: "phrasal-verbs",
    aiKeywords: ["Separable phrasal verbs", "Inseparable phrasal verbs", "Transitive/intransitive phrasal verbs", "Common phrasal verbs"],
  },
  {
    id: "g-b1-14",
    level: "B1-B2",
    category: "Phrasal Verbs & Collocations",
    titleEn: "Collocations",
    titleVi: "Kết hợp từ (Collocations)",
    description: "Những từ thường đi cùng nhau tự nhiên: make/do, strong tea, heavy rain.",
    slug: "collocations",
    aiKeywords: ["Verb + noun collocations", "Adjective + noun collocations", "make vs do", "Common collocations"],
  },
  {
    id: "g-b1-15",
    level: "B1-B2",
    category: "Sentence Structures",
    titleEn: "Linking Words and Discourse Markers",
    titleVi: "Từ nối và Dấu hiệu liên kết",
    description: "however, therefore, although, in addition… nối ý mạch lạc khi viết.",
    slug: "linking-words",
    aiKeywords: ["Contrast linkers (however, although)", "Addition linkers (moreover)", "Cause/result (therefore)", "Discourse markers for writing"],
  },
  {
    id: "g-a1-15",
    level: "A1-A2",
    category: "Modifiers",
    titleEn: "Order of Adjectives",
    titleVi: "Trật tự Tính từ",
    description: "Thứ tự khi nhiều tính từ bổ nghĩa cho một danh từ: opinion-size-age-shape-color…",
    slug: "order-of-adjectives",
    aiKeywords: ["Order of adjectives", "Opinion before fact", "OSASCOMP", "Multiple adjectives"],
  },
  {
    id: "g-b1-16",
    level: "B1-B2",
    category: "Prepositions",
    titleEn: "Prepositions of Movement & Direction",
    titleVi: "Giới từ chỉ Chuyển động & Phương hướng",
    description: "to, into, onto, through, across, towards… diễn tả hướng và chuyển động.",
    slug: "prepositions-movement",
    aiKeywords: ["Prepositions of movement", "into vs in", "across vs through", "towards/onto"],
  },
  {
    id: "g-b1-17",
    level: "B1-B2",
    category: "Prepositions",
    titleEn: "Dependent Prepositions",
    titleVi: "Giới từ đi kèm (Dependent Prepositions)",
    description: "Giới từ cố định sau động từ/tính từ/danh từ: depend on, good at, interested in.",
    slug: "dependent-prepositions",
    aiKeywords: ["Verb + preposition", "Adjective + preposition", "Noun + preposition", "Common dependent prepositions"],
  },
  {
    id: "g-b1-18",
    level: "B1-B2",
    category: "Modifiers",
    titleEn: "Participial Adjectives (-ed vs -ing)",
    titleVi: "Tính từ đuôi -ed và -ing",
    description: "Phân biệt bored/boring, interested/interesting: cảm nhận vs tính chất gây ra.",
    slug: "participial-adjectives",
    aiKeywords: ["-ed adjectives feeling", "-ing adjectives quality", "bored vs boring", "interested vs interesting"],
  },
  {
    id: "g-b1-19",
    level: "B1-B2",
    category: "Sentence Structures",
    titleEn: "Compound and Complex Sentences",
    titleVi: "Câu ghép và Câu phức",
    description: "Nối mệnh đề bằng and/but/or (ghép) và liên từ phụ thuộc when/because/although (phức).",
    slug: "compound-complex-sentences",
    aiKeywords: ["Compound sentences", "Complex sentences", "Coordinating conjunctions", "Subordinating conjunctions"],
  },

  // ===== BỔ SUNG ĐỢT 2 =====
  {
    id: "g-a1-16",
    level: "A1-A2",
    category: "Nouns & Pronouns",
    titleEn: "Reflexive and Indefinite Pronouns",
    titleVi: "Đại từ Phản thân và Bất định",
    description: "myself/yourself… và somebody/anything/everyone/nowhere.",
    slug: "reflexive-indefinite-pronouns",
    aiKeywords: ["Reflexive pronouns", "Indefinite pronouns", "someone/anyone/no one", "by myself"],
  },
  {
    id: "g-a1-17",
    level: "A1-A2",
    category: "Nouns & Pronouns",
    titleEn: "Possessive Forms ('s and of)",
    titleVi: "Sở hữu cách ('s và of)",
    description: "John's book vs the leg of the table; sở hữu kép.",
    slug: "possessive-forms",
    aiKeywords: ["Apostrophe s", "of-genitive", "Possessive with people vs things", "Double possessive"],
  },
  {
    id: "g-a1-18",
    level: "A1-A2",
    category: "Modifiers",
    titleEn: "Adverbs of Frequency and Place",
    titleVi: "Trạng từ Tần suất và Nơi chốn",
    description: "always/usually/sometimes/never và vị trí trạng từ trong câu.",
    slug: "adverbs-frequency-place",
    aiKeywords: ["Adverbs of frequency", "Position of adverbs", "always/usually/never", "Adverbs of place"],
  },
  {
    id: "g-a1-19",
    level: "A1-A2",
    category: "Modals",
    titleEn: "Modals of Ability and Permission",
    titleVi: "Động từ Khuyết thiếu: Khả năng & Xin phép",
    description: "can/could/may diễn tả khả năng, xin phép, lời đề nghị lịch sự.",
    slug: "modals-ability-permission",
    aiKeywords: ["can/could ability", "may/can permission", "Polite requests", "be able to"],
  },
  {
    id: "g-a1-20",
    level: "A1-A2",
    category: "Phrasal Verbs & Collocations",
    titleEn: "Confusing Word Pairs",
    titleVi: "Cặp từ dễ nhầm",
    description: "make/do, say/tell, lend/borrow, fun/funny, this/these…",
    slug: "confusing-word-pairs",
    aiKeywords: ["make vs do", "say vs tell", "lend vs borrow", "Commonly confused words"],
  },
  {
    id: "g-b1-20",
    level: "B1-B2",
    category: "Articles & Determiners",
    titleEn: "The Zero Article",
    titleVi: "Mạo từ Zero (không dùng mạo từ)",
    description: "Khi nào KHÔNG dùng a/an/the: danh từ chung, tên riêng, bữa ăn…",
    slug: "zero-article",
    aiKeywords: ["Zero article", "No article with plurals/uncountables", "Proper nouns", "Generalizations"],
  },
  {
    id: "g-b1-21",
    level: "B1-B2",
    category: "Verbs & Tenses",
    titleEn: "Present Perfect Continuous",
    titleVi: "Thì Hiện tại Hoàn thành Tiếp diễn",
    description: "have/has been V-ing — nhấn mạnh quá trình kéo dài tới hiện tại.",
    slug: "present-perfect-continuous",
    aiKeywords: ["have been V-ing", "Duration with for/since", "Perfect simple vs continuous", "Ongoing result"],
  },
  {
    id: "g-b1-22",
    level: "B1-B2",
    category: "Sentence Structures",
    titleEn: "Word Order and Adverb Placement",
    titleVi: "Trật tự từ và Vị trí Trạng từ",
    description: "SVO, trật tự trạng từ cách thức – nơi chốn – thời gian.",
    slug: "word-order",
    aiKeywords: ["SVO order", "Manner place time order", "Mid-position adverbs", "End-position adverbs"],
  },
  {
    id: "g-b1-23",
    level: "B1-B2",
    category: "Voice & Speech",
    titleEn: "Reported Questions and Commands",
    titleVi: "Câu Tường thuật: Câu hỏi & Mệnh lệnh",
    description: "asked if/whether, asked wh-; told/asked sb to (not) do.",
    slug: "reported-questions-commands",
    aiKeywords: ["Reported yes/no questions", "Reported wh-questions", "Reported commands", "tell/ask + to-infinitive"],
  },
  {
    id: "g-b1-24",
    level: "B1-B2",
    category: "Voice & Speech",
    titleEn: "The Causative (have/get something done)",
    titleVi: "Thể Sai khiến (have/get something done)",
    description: "have my hair cut, get the car repaired; nhờ/khiến ai làm gì.",
    slug: "causative",
    aiKeywords: ["have something done", "get something done", "Causative passive", "make/let/have someone do"],
  },
  {
    id: "g-b1-25",
    level: "B1-B2",
    category: "Clauses",
    titleEn: "Noun Clauses",
    titleVi: "Mệnh đề Danh ngữ",
    description: "that-clause và wh-clause làm chủ ngữ, tân ngữ hoặc bổ ngữ.",
    slug: "noun-clauses",
    aiKeywords: ["That-clauses", "Wh-clauses", "Noun clause as subject/object", "if/whether clauses"],
  },
  {
    id: "g-b1-26",
    level: "B1-B2",
    category: "Clauses",
    titleEn: "Adverbial Clauses of Time and Reason",
    titleVi: "Mệnh đề Trạng ngữ (Thời gian & Lý do)",
    description: "when/while/as soon as/until và because/since/as.",
    slug: "adverbial-clauses",
    aiKeywords: ["Time clauses", "Reason clauses", "when/while/as soon as", "because/since/as"],
  },
  {
    id: "g-b1-27",
    level: "B1-B2",
    category: "Modals",
    titleEn: "Semi-modals (need to, ought to, had better)",
    titleVi: "Bán Động từ Khuyết thiếu",
    description: "need to, ought to, had better, would rather — sắc thái lời khuyên.",
    slug: "semi-modals",
    aiKeywords: ["had better", "ought to", "need to / needn't", "would rather"],
  },
  {
    id: "g-b1-28",
    level: "B1-B2",
    category: "Verb Forms",
    titleEn: "Bare and To-infinitive Uses",
    titleVi: "Nguyên mẫu có 'to' và không 'to'",
    description: "make/let/help + V-bare; want/decide/hope + to-V; sau giác quan.",
    slug: "infinitive-uses",
    aiKeywords: ["Bare infinitive after make/let", "to-infinitive after verbs", "Verbs of perception", "help + (to) V"],
  },
  {
    id: "g-b1-29",
    level: "B1-B2",
    category: "Phrasal Verbs & Collocations",
    titleEn: "Idioms and Fixed Expressions",
    titleVi: "Thành ngữ và Cụm cố định",
    description: "break the ice, once in a blue moon, hit the books…",
    slug: "idioms",
    aiKeywords: ["Common English idioms", "Fixed expressions", "Idiom meaning in context", "Binomials"],
  },

  // ===== BỔ SUNG ĐỢT 3 =====
  {
    id: "g-a1-21",
    level: "A1-A2",
    category: "Articles & Determiners",
    titleEn: "Quantifiers: much, many, a few, a little",
    titleVi: "Lượng từ: much, many, a few, a little",
    description: "Đếm được vs không đếm được; some/any; (a) few / (a) little.",
    slug: "quantifiers-much-many",
    aiKeywords: ["much vs many", "a few vs few", "a little vs little", "some/any"],
  },
  {
    id: "g-b1-30",
    level: "B1-B2",
    category: "Verbs & Tenses",
    titleEn: "Used to / Would (past habits)",
    titleVi: "Used to / Would — thói quen trong quá khứ",
    description: "used to + V, would + V cho thói quen xưa; phân biệt be used to.",
    slug: "used-to-would",
    aiKeywords: ["used to + infinitive", "would for repeated past", "be/get used to + V-ing", "Past habits"],
  },
  {
    id: "g-b1-31",
    level: "B1-B2",
    category: "Modifiers",
    titleEn: "Intensifiers and Degree Adverbs",
    titleVi: "Trạng từ Mức độ (very, quite, rather, too, enough)",
    description: "very/really/quite/rather + tính từ; too… vs … enough.",
    slug: "intensifiers",
    aiKeywords: ["very/really/quite/rather", "too + adj", "adj + enough", "Gradable vs non-gradable"],
  },
  {
    id: "g-b1-32",
    level: "B1-B2",
    category: "Voice & Speech",
    titleEn: "Passive with Reporting Verbs",
    titleVi: "Bị động với Động từ Tường thuật (It is said that…)",
    description: "It is said that… / He is said to… — bị động kép trang trọng.",
    slug: "passive-reporting",
    aiKeywords: ["It is said that", "He is believed to", "Double passive", "Reporting verb passive"],
  },
  {
    id: "g-b1-33",
    level: "B1-B2",
    category: "Clauses",
    titleEn: "Clauses of Concession and Purpose",
    titleVi: "Mệnh đề Nhượng bộ & Mục đích",
    description: "although/even though/though; so that / in order to / so as to.",
    slug: "concession-purpose-clauses",
    aiKeywords: ["although/even though", "despite/in spite of", "so that / in order to", "Concession vs purpose"],
  },
  {
    id: "g-b1-34",
    level: "B1-B2",
    category: "Conditionals",
    titleEn: "Conditional Connectors (unless, provided, as long as)",
    titleVi: "Liên từ Điều kiện (unless, provided, as long as)",
    description: "unless = if not; provided/providing, as long as, in case.",
    slug: "conditional-connectors",
    aiKeywords: ["unless", "provided/providing that", "as long as", "in case"],
  },
  {
    id: "g-b1-35",
    level: "B1-B2",
    category: "Verb Forms",
    titleEn: "Verb Patterns (verb + object + to-V / V-ing)",
    titleVi: "Mẫu Động từ (verb + tân ngữ + to-V / V-ing)",
    description: "want sb to do, make sb do, see sb doing — các mẫu đi kèm tân ngữ.",
    slug: "verb-patterns",
    aiKeywords: ["verb + object + to-infinitive", "verb + object + bare infinitive", "verb + object + V-ing", "Perception verbs"],
  },
  {
    id: "g-b1-36",
    level: "B1-B2",
    category: "Phrasal Verbs & Collocations",
    titleEn: "Three-part Phrasal Verbs",
    titleVi: "Cụm động từ Ba thành phần",
    description: "look forward to, put up with, get on with… động từ + 2 tiểu từ.",
    slug: "three-part-phrasal-verbs",
    aiKeywords: ["Three-part phrasal verbs", "look forward to", "put up with", "get on with"],
  },
  {
    id: "g-c1-11",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Nominalisation (Academic Style)",
    titleVi: "Danh từ hoá (văn phong học thuật)",
    description: "Biến động từ/tính từ thành danh từ để viết trang trọng, súc tích.",
    slug: "nominalisation",
    aiKeywords: ["Nominalisation", "Verb to noun", "Academic register", "Abstract nouns"],
  },
  {
    id: "g-c1-12",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Hedging and Cautious Language",
    titleVi: "Ngôn ngữ Rào đón / Thận trọng (Hedging)",
    description: "may/tend to/it appears that… giảm nhẹ khẳng định trong văn học thuật.",
    slug: "hedging",
    aiKeywords: ["Hedging language", "modals for caution", "tend to / appear to", "Softening claims"],
  },
  {
    id: "g-c1-13",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Cohesion and Referencing",
    titleVi: "Liên kết & Quy chiếu (this, such, the former)",
    description: "this/that/such, the former/the latter, đại từ quy chiếu nối ý.",
    slug: "cohesion-referencing",
    aiKeywords: ["Reference words", "this/such referencing", "former/latter", "Cohesive devices"],
  },
  {
    id: "g-c1-14",
    level: "C1-C2",
    category: "Advanced Structures",
    titleEn: "Parallel Structure",
    titleVi: "Cấu trúc Song song (Parallelism)",
    description: "Giữ các thành phần đồng dạng trong liệt kê/so sánh để mạch lạc.",
    slug: "parallelism",
    aiKeywords: ["Parallel structure", "Parallelism in lists", "Correlative conjunctions", "not only... but also"],
  },
];

export const grammarBySlug = (slug: string): GrammarLesson | undefined =>
  grammarLessons.find((l) => l.slug === slug);

// Tên tiếng Việt cho các chủ đề (category) — dùng cho view "Theo chủ đề".
export const CATEGORY_VI: Record<string, string> = {
  "Nouns & Pronouns": "Danh từ & Đại từ",
  "Articles & Determiners": "Mạo từ & Từ hạn định",
  "Verbs & Tenses": "Động từ & Thì",
  "Modifiers": "Tính từ & Trạng từ",
  "Prepositions": "Giới từ",
  "Sentence Structures": "Cấu trúc câu",
  "Voice & Speech": "Bị động & Tường thuật",
  "Clauses": "Mệnh đề",
  "Conditionals": "Câu điều kiện",
  "Modals": "Động từ khuyết thiếu",
  "Verb Forms": "Dạng động từ (V-ing / to-V)",
  "Advanced Structures": "Cấu trúc nâng cao",
  "Phrasal Verbs & Collocations": "Cụm động từ & Kết hợp từ",
};
