// A pool of ~100 popular topics (world trends + exam themes + everyday life +
// business) used to pick a RANDOM topic when the user leaves the topic blank.
// Topics are English phrases since they feed English-content generation.

export const TOPIC_POOL: string[] = [
  // World / trending / exam
  "Climate change",
  "Artificial intelligence",
  "Renewable energy",
  "Space exploration",
  "Globalization",
  "Social media",
  "Cybersecurity",
  "Online privacy",
  "Fake news and misinformation",
  "Electric vehicles",
  "Plastic pollution",
  "Mental health",
  "Public health",
  "Vaccines",
  "Urbanization",
  "Deforestation",
  "Water scarcity",
  "Automation and the future of work",
  "Aging populations",
  "Gender equality",
  "Income inequality",
  "Cultural diversity",
  "Endangered species",
  "Sustainable fashion",
  "Food security",
  "Smart cities",
  "Digital currency",
  "Virtual reality",
  "Robotics",
  "Biotechnology",
  "Genetic engineering",
  "Renewable vs fossil fuels",
  "Education technology",
  "Distance learning",
  "Lifelong learning",
  "Standardized testing",
  "Studying abroad",
  "The gig economy",
  "Tourism and the environment",
  "Overpopulation",
  // Everyday life
  "Daily routines",
  "Hobbies and interests",
  "Family relationships",
  "Friendship",
  "Healthy eating",
  "Exercise and fitness",
  "Travel and tourism",
  "Cooking and recipes",
  "Pets and animals",
  "Weather and seasons",
  "Shopping habits",
  "Music and concerts",
  "Movies and cinema",
  "Books and reading",
  "Sports",
  "Festivals and holidays",
  "Fashion and style",
  "Photography",
  "Gardening",
  "Video games",
  "Coffee culture",
  "Public transport",
  "City life vs countryside",
  "Weekend activities",
  "Childhood memories",
  "Learning a new language",
  "Time management",
  "Sleep and rest",
  "Volunteering",
  "Social etiquette",
  "Online shopping",
  "Streaming and entertainment",
  "Houses and homes",
  "Neighbourhoods",
  "Transport and traffic",
  "Personal goals",
  "Dreams and ambitions",
  "Memorable trips",
  "Favourite places",
  "Everyday technology",
  // Business / office
  "Job interviews",
  "Writing a resume",
  "Career development",
  "Remote work",
  "Teamwork",
  "Leadership",
  "Marketing strategies",
  "Startups",
  "Entrepreneurship",
  "Customer service",
  "Work-life balance",
  "Office communication",
  "Writing business emails",
  "Negotiation",
  "Personal finance",
  "Investing",
  "Budgeting and saving",
  "Productivity",
  "Professional networking",
  "Brand building",
  "E-commerce",
  "Advertising",
  "Project management",
  "Workplace culture",
  "Public speaking",
];

/** Random topic from the pool, optionally avoiding one value (e.g. the last). */
export function randomTopic(avoid?: string): string {
  const pool = avoid ? TOPIC_POOL.filter((t) => t !== avoid) : TOPIC_POOL;
  const i = Math.floor(Math.random() * pool.length);
  return pool[i] ?? TOPIC_POOL[0];
}
